# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ulsu1AubCE4wiKr9kLH_n91J62gYL197
"""

rooms = {
    "A": "Dirty",
    "B": "Clean",
    "C": "Dirty",
    "D": "Dirty"
}

location = "A"
step = 1

while "Dirty" in rooms.values():

    current_location = location

    if rooms[location] == "Dirty":
        action = "Suck"
        rooms[location] = "Clean"

    elif location == "A":
        action = "Down"
        location = "C"

    elif location == "C":
        action = "Right"
        location = "D"

    elif location == "D":
        action = "Up"
        location = "B"

    elif location == "B":
        action = "Left"
        location = "A"

    print("Step", step)
    print("Current Location:", current_location)
    print("Selected Action:", action)
    print()

    step += 1

print("All rooms are clean!")
print("Cleaning completed.")